INSERT INTO STATION(ID, NAME)
    VALUES (1, '잠실');
INSERT INTO STATION(ID, NAME)
    VALUES (2, '교대');
INSERT INTO STATION(ID, NAME)
    VALUES (3, '강남');
INSERT INTO LINE(ID, NAME, START_TIME, END_TIME, INTERVAL_TIME)
    VALUES (1, '2호선', '10:00:00', '10:00:00', 1);
INSERT INTO LINE(ID, NAME, START_TIME, END_TIME, INTERVAL_TIME)
    VALUES (2, '3호선', '10:00:00', '10:00:00', 1);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (1, 1, 1, 0, 0);