INSERT INTO STATION(NAME)
    VALUES ('잠실역');
INSERT INTO STATION(NAME)
    VALUES ('역삼역');
INSERT INTO STATION(NAME)
    VALUES ('선릉역');
INSERT INTO STATION(NAME)
    VALUES ('양재역');
INSERT INTO STATION(NAME)
    VALUES ('양재시민의숲역');
INSERT INTO LINE(NAME, START_TIME, END_TIME, INTERVAL_TIME)
    VALUES ('1호선', '10:00:00', '10:00:00', 1);
INSERT INTO LINE(NAME, START_TIME, END_TIME, INTERVAL_TIME)
    VALUES ('2호선', '10:00:00', '10:00:00', 1);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (1, null, 1, 10, 10);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (1, 1, 2, 10, 10);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (1, 2, 3, 10, 10);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (2, null, 1, 10, 10);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (2, 1, 4, 10, 10);
INSERT INTO LINE_STATION(LINE, PRE_STATION_ID, STATION_ID, DISTANCE, DURATION)
    VALUES (2, 4, 5, 10, 10);