SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE LINE;
TRUNCATE TABLE SECTION;
TRUNCATE TABLE STATION;
ALTER TABLE LINE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE SECTION ALTER COLUMN id RESTART WITH 1;
ALTER TABLE StATION ALTER COLUMN id RESTART WITH 1;
